### ISSUE TITLE
Giving pages. 

### ISSUE THREAD

**Issue by camrun91** [CrossingsCommunityChurch/RockTheme#46] opened 2020-07-06 15:18 UTC
Need to set up pages for users to see and manage giving.

**Comment by camrun91** [comment] 2020-07-19 13:08
@wesgate I think you are working on modifying this currently?

**Comment by wesgate** [comment] 2020-07-19 15:22
@camrun91 there are two separate issues for this. I have a different one open for styling already but I think you created this one initially to setup the giving pages, payment gateways/ make a contribution page, the backend part of the giving to make sure it was setup correctly (listing proper accounts for people to give to, etc) and that stuff. if you don't need it anymore or if it was intended for styling you can just mark it as a duplicate and close it

**Closed** 2020-07-27 04:52 UTC
Labels: backend, frontend
